// Nantian Gateway AI Service Configuration
//
// This file defines AI/LLM provider proxy configuration types for the
// data plane to intercept and transform requests into provider-specific
// API calls (OpenAI, Anthropic, Ollama, etc.).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: gateway/control/v1/ai.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AIServiceConfig configures an AI/LLM provider proxy for a backend cluster.
// The data plane intercepts requests matching this backend and transforms
// them into provider-specific API calls (OpenAI, Anthropic, Ollama, etc.).
type AIServiceConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AI provider identifier (e.g. "openai", "anthropic", "ollama").
	Provider string `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	// API format for request/response transformation (e.g. "openai-chat", "anthropic-messages").
	Format string `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	// Default model name to use if not specified in the request.
	Model string `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	// Authentication configuration for the AI provider API.
	Auth *AIServiceAuthConfig `protobuf:"bytes,4,opt,name=auth,proto3" json:"auth,omitempty"`
	// Timeout for AI provider API calls.
	Timeout *durationpb.Duration `protobuf:"bytes,5,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Optional endpoint URL override for the AI provider API.
	// If empty, the data plane uses the provider's default endpoint.
	Endpoint string `protobuf:"bytes,6,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// Maximum number of retry attempts for transient failures.
	RetryMaxRetries uint32 `protobuf:"varint,7,opt,name=retry_max_retries,json=retryMaxRetries,proto3" json:"retry_max_retries,omitempty"`
	// Base backoff duration between retries.
	RetryBackoff  *durationpb.Duration `protobuf:"bytes,8,opt,name=retry_backoff,json=retryBackoff,proto3" json:"retry_backoff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIServiceConfig) Reset() {
	*x = AIServiceConfig{}
	mi := &file_gateway_control_v1_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIServiceConfig) ProtoMessage() {}

func (x *AIServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_v1_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIServiceConfig.ProtoReflect.Descriptor instead.
func (*AIServiceConfig) Descriptor() ([]byte, []int) {
	return file_gateway_control_v1_ai_proto_rawDescGZIP(), []int{0}
}

func (x *AIServiceConfig) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *AIServiceConfig) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *AIServiceConfig) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AIServiceConfig) GetAuth() *AIServiceAuthConfig {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *AIServiceConfig) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *AIServiceConfig) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *AIServiceConfig) GetRetryMaxRetries() uint32 {
	if x != nil {
		return x.RetryMaxRetries
	}
	return 0
}

func (x *AIServiceConfig) GetRetryBackoff() *durationpb.Duration {
	if x != nil {
		return x.RetryBackoff
	}
	return nil
}

// AIServiceAuthConfig specifies how the data plane authenticates to an AI provider API.
type AIServiceAuthConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Authentication type: "bearer", "api-key", or "basic".
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Reference to a SecretMaterial or Kubernetes Secret containing the credential.
	SecretRef string `protobuf:"bytes,2,opt,name=secret_ref,json=secretRef,proto3" json:"secret_ref,omitempty"`
	// HTTP header name to inject the credential into (e.g. "Authorization", "x-api-key").
	Header string `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	// Key within the Kubernetes Secret to read the credential from.
	Key           string `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIServiceAuthConfig) Reset() {
	*x = AIServiceAuthConfig{}
	mi := &file_gateway_control_v1_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIServiceAuthConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIServiceAuthConfig) ProtoMessage() {}

func (x *AIServiceAuthConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_v1_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIServiceAuthConfig.ProtoReflect.Descriptor instead.
func (*AIServiceAuthConfig) Descriptor() ([]byte, []int) {
	return file_gateway_control_v1_ai_proto_rawDescGZIP(), []int{1}
}

func (x *AIServiceAuthConfig) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AIServiceAuthConfig) GetSecretRef() string {
	if x != nil {
		return x.SecretRef
	}
	return ""
}

func (x *AIServiceAuthConfig) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *AIServiceAuthConfig) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// TokenPolicyConfig defines token-based rate limiting for AI model calls.
type TokenPolicyConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum tokens allowed per minute.
	TokensPerMinute uint64 `protobuf:"varint,1,opt,name=tokens_per_minute,json=tokensPerMinute,proto3" json:"tokens_per_minute,omitempty"`
	// Maximum tokens allowed per hour.
	TokensPerHour uint64 `protobuf:"varint,2,opt,name=tokens_per_hour,json=tokensPerHour,proto3" json:"tokens_per_hour,omitempty"`
	// Maximum requests allowed per minute.
	RequestsPerMinute uint64 `protobuf:"varint,3,opt,name=requests_per_minute,json=requestsPerMinute,proto3" json:"requests_per_minute,omitempty"`
	// Scope of the rate limit: "global" (across all clients) or "per-user".
	Scope string `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	// Burst multiplier: allowed short-term overshoot as a ratio of the rate limit.
	Burst float64 `protobuf:"fixed64,5,opt,name=burst,proto3" json:"burst,omitempty"`
	// Action when limit is exceeded: "reject" (429), "queue", or "degrade".
	OnLimit       string `protobuf:"bytes,6,opt,name=on_limit,json=onLimit,proto3" json:"on_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenPolicyConfig) Reset() {
	*x = TokenPolicyConfig{}
	mi := &file_gateway_control_v1_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPolicyConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPolicyConfig) ProtoMessage() {}

func (x *TokenPolicyConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_v1_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPolicyConfig.ProtoReflect.Descriptor instead.
func (*TokenPolicyConfig) Descriptor() ([]byte, []int) {
	return file_gateway_control_v1_ai_proto_rawDescGZIP(), []int{2}
}

func (x *TokenPolicyConfig) GetTokensPerMinute() uint64 {
	if x != nil {
		return x.TokensPerMinute
	}
	return 0
}

func (x *TokenPolicyConfig) GetTokensPerHour() uint64 {
	if x != nil {
		return x.TokensPerHour
	}
	return 0
}

func (x *TokenPolicyConfig) GetRequestsPerMinute() uint64 {
	if x != nil {
		return x.RequestsPerMinute
	}
	return 0
}

func (x *TokenPolicyConfig) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *TokenPolicyConfig) GetBurst() float64 {
	if x != nil {
		return x.Burst
	}
	return 0
}

func (x *TokenPolicyConfig) GetOnLimit() string {
	if x != nil {
		return x.OnLimit
	}
	return ""
}

var File_gateway_control_v1_ai_proto protoreflect.FileDescriptor

const file_gateway_control_v1_ai_proto_rawDesc = "" +
	"\n" +
	"\x1bgateway/control/v1/ai.proto\x12\x12gateway.control.v1\x1a\x1egoogle/protobuf/duration.proto\"\xd5\x02\n" +
	"\x0fAIServiceConfig\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12;\n" +
	"\x04auth\x18\x04 \x01(\v2'.gateway.control.v1.AIServiceAuthConfigR\x04auth\x123\n" +
	"\atimeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12\x1a\n" +
	"\bendpoint\x18\x06 \x01(\tR\bendpoint\x12*\n" +
	"\x11retry_max_retries\x18\a \x01(\rR\x0fretryMaxRetries\x12>\n" +
	"\rretry_backoff\x18\b \x01(\v2\x19.google.protobuf.DurationR\fretryBackoff\"r\n" +
	"\x13AIServiceAuthConfig\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"secret_ref\x18\x02 \x01(\tR\tsecretRef\x12\x16\n" +
	"\x06header\x18\x03 \x01(\tR\x06header\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\"\xde\x01\n" +
	"\x11TokenPolicyConfig\x12*\n" +
	"\x11tokens_per_minute\x18\x01 \x01(\x04R\x0ftokensPerMinute\x12&\n" +
	"\x0ftokens_per_hour\x18\x02 \x01(\x04R\rtokensPerHour\x12.\n" +
	"\x13requests_per_minute\x18\x03 \x01(\x04R\x11requestsPerMinute\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12\x14\n" +
	"\x05burst\x18\x05 \x01(\x01R\x05burst\x12\x19\n" +
	"\bon_limit\x18\x06 \x01(\tR\aonLimitB:Z8github.com/nantian-gw/proto/gateway/control/v1;controlv1b\x06proto3"

var (
	file_gateway_control_v1_ai_proto_rawDescOnce sync.Once
	file_gateway_control_v1_ai_proto_rawDescData []byte
)

func file_gateway_control_v1_ai_proto_rawDescGZIP() []byte {
	file_gateway_control_v1_ai_proto_rawDescOnce.Do(func() {
		file_gateway_control_v1_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_control_v1_ai_proto_rawDesc), len(file_gateway_control_v1_ai_proto_rawDesc)))
	})
	return file_gateway_control_v1_ai_proto_rawDescData
}

var file_gateway_control_v1_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_gateway_control_v1_ai_proto_goTypes = []any{
	(*AIServiceConfig)(nil),     // 0: gateway.control.v1.AIServiceConfig
	(*AIServiceAuthConfig)(nil), // 1: gateway.control.v1.AIServiceAuthConfig
	(*TokenPolicyConfig)(nil),   // 2: gateway.control.v1.TokenPolicyConfig
	(*durationpb.Duration)(nil), // 3: google.protobuf.Duration
}
var file_gateway_control_v1_ai_proto_depIdxs = []int32{
	1, // 0: gateway.control.v1.AIServiceConfig.auth:type_name -> gateway.control.v1.AIServiceAuthConfig
	3, // 1: gateway.control.v1.AIServiceConfig.timeout:type_name -> google.protobuf.Duration
	3, // 2: gateway.control.v1.AIServiceConfig.retry_backoff:type_name -> google.protobuf.Duration
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_gateway_control_v1_ai_proto_init() }
func file_gateway_control_v1_ai_proto_init() {
	if File_gateway_control_v1_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_control_v1_ai_proto_rawDesc), len(file_gateway_control_v1_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_control_v1_ai_proto_goTypes,
		DependencyIndexes: file_gateway_control_v1_ai_proto_depIdxs,
		MessageInfos:      file_gateway_control_v1_ai_proto_msgTypes,
	}.Build()
	File_gateway_control_v1_ai_proto = out.File
	file_gateway_control_v1_ai_proto_goTypes = nil
	file_gateway_control_v1_ai_proto_depIdxs = nil
}
