// Nantian Gateway xDS Control-Plane Protocol
//
// This is the umbrella file for the gateway.control.v1 package.
// All type definitions have been split into domain-specific files:
//
//   discovery.proto  — DiscoveryService, DeltaDiscoveryService, discovery messages
//   config.proto     — ConfigSnapshot, listeners, routes, backends, TLS, session persistence
//   ai.proto         — AIServiceConfig, TokenPolicyConfig
//   wasm.proto       — WasmPluginConfig, WasmSandboxConfig
//   route_policy.proto — RoutePolicy, RoutePolicyTimeout, etc.
//
// This file imports all domain files and re-exports the package for
// backward compatibility. New code should import the specific domain
// file instead of this umbrella.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: gateway/control/v1/control.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_gateway_control_v1_control_proto protoreflect.FileDescriptor

const file_gateway_control_v1_control_proto_rawDesc = "" +
	"\n" +
	" gateway/control/v1/control.proto\x12\x12gateway.control.v1\x1a\x1bgateway/control/v1/ai.proto\x1a\x1fgateway/control/v1/config.proto\x1a\"gateway/control/v1/discovery.proto\x1a%gateway/control/v1/route_policy.proto\x1a\x1dgateway/control/v1/wasm.protoB:Z8github.com/nantian-gw/proto/gateway/control/v1;controlv1b\x06proto3"

var file_gateway_control_v1_control_proto_goTypes = []any{}
var file_gateway_control_v1_control_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_control_v1_control_proto_init() }
func file_gateway_control_v1_control_proto_init() {
	if File_gateway_control_v1_control_proto != nil {
		return
	}
	file_gateway_control_v1_ai_proto_init()
	file_gateway_control_v1_config_proto_init()
	file_gateway_control_v1_discovery_proto_init()
	file_gateway_control_v1_route_policy_proto_init()
	file_gateway_control_v1_wasm_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_control_v1_control_proto_rawDesc), len(file_gateway_control_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_control_v1_control_proto_goTypes,
		DependencyIndexes: file_gateway_control_v1_control_proto_depIdxs,
	}.Build()
	File_gateway_control_v1_control_proto = out.File
	file_gateway_control_v1_control_proto_goTypes = nil
	file_gateway_control_v1_control_proto_depIdxs = nil
}
