// Nantian Gateway xDS Discovery Service Protocol
//
// This file defines the gRPC-based xDS (discovery service) contract between
// the Go control plane and Rust data plane, including the streaming
// configuration protocol, delta (incremental) discovery, and status reporting.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: gateway/control/v1/discovery.proto

package controlv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConfigurationDiscoveryService_StreamConfiguration_FullMethodName = "/gateway.control.v1.ConfigurationDiscoveryService/StreamConfiguration"
	ConfigurationDiscoveryService_ReportStatus_FullMethodName        = "/gateway.control.v1.ConfigurationDiscoveryService/ReportStatus"
)

// ConfigurationDiscoveryServiceClient is the client API for ConfigurationDiscoveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConfigurationDiscoveryService is the core xDS control-plane API.
// Data-plane instances use this service to receive configuration
// and report operational status back to the control plane.
type ConfigurationDiscoveryServiceClient interface {
	// StreamConfiguration establishes a bi-directional stream for xDS
	// configuration delivery. The data plane sends DiscoveryRequest
	// messages to subscribe to resources; the control plane responds
	// with DiscoveryResponse messages containing ConfigSnapshots.
	StreamConfiguration(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DiscoveryRequest, DiscoveryResponse], error)
	// ReportStatus allows the data plane to report its health and readiness
	// to the control plane. Called periodically (typically every 10-30s).
	ReportStatus(ctx context.Context, in *StatusReport, opts ...grpc.CallOption) (*StatusAck, error)
}

type configurationDiscoveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigurationDiscoveryServiceClient(cc grpc.ClientConnInterface) ConfigurationDiscoveryServiceClient {
	return &configurationDiscoveryServiceClient{cc}
}

func (c *configurationDiscoveryServiceClient) StreamConfiguration(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DiscoveryRequest, DiscoveryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConfigurationDiscoveryService_ServiceDesc.Streams[0], ConfigurationDiscoveryService_StreamConfiguration_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DiscoveryRequest, DiscoveryResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigurationDiscoveryService_StreamConfigurationClient = grpc.BidiStreamingClient[DiscoveryRequest, DiscoveryResponse]

func (c *configurationDiscoveryServiceClient) ReportStatus(ctx context.Context, in *StatusReport, opts ...grpc.CallOption) (*StatusAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusAck)
	err := c.cc.Invoke(ctx, ConfigurationDiscoveryService_ReportStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigurationDiscoveryServiceServer is the server API for ConfigurationDiscoveryService service.
// All implementations must embed UnimplementedConfigurationDiscoveryServiceServer
// for forward compatibility.
//
// ConfigurationDiscoveryService is the core xDS control-plane API.
// Data-plane instances use this service to receive configuration
// and report operational status back to the control plane.
type ConfigurationDiscoveryServiceServer interface {
	// StreamConfiguration establishes a bi-directional stream for xDS
	// configuration delivery. The data plane sends DiscoveryRequest
	// messages to subscribe to resources; the control plane responds
	// with DiscoveryResponse messages containing ConfigSnapshots.
	StreamConfiguration(grpc.BidiStreamingServer[DiscoveryRequest, DiscoveryResponse]) error
	// ReportStatus allows the data plane to report its health and readiness
	// to the control plane. Called periodically (typically every 10-30s).
	ReportStatus(context.Context, *StatusReport) (*StatusAck, error)
	mustEmbedUnimplementedConfigurationDiscoveryServiceServer()
}

// UnimplementedConfigurationDiscoveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigurationDiscoveryServiceServer struct{}

func (UnimplementedConfigurationDiscoveryServiceServer) StreamConfiguration(grpc.BidiStreamingServer[DiscoveryRequest, DiscoveryResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamConfiguration not implemented")
}
func (UnimplementedConfigurationDiscoveryServiceServer) ReportStatus(context.Context, *StatusReport) (*StatusAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportStatus not implemented")
}
func (UnimplementedConfigurationDiscoveryServiceServer) mustEmbedUnimplementedConfigurationDiscoveryServiceServer() {
}
func (UnimplementedConfigurationDiscoveryServiceServer) testEmbeddedByValue() {}

// UnsafeConfigurationDiscoveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigurationDiscoveryServiceServer will
// result in compilation errors.
type UnsafeConfigurationDiscoveryServiceServer interface {
	mustEmbedUnimplementedConfigurationDiscoveryServiceServer()
}

func RegisterConfigurationDiscoveryServiceServer(s grpc.ServiceRegistrar, srv ConfigurationDiscoveryServiceServer) {
	// If the following call panics, it indicates UnimplementedConfigurationDiscoveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigurationDiscoveryService_ServiceDesc, srv)
}

func _ConfigurationDiscoveryService_StreamConfiguration_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConfigurationDiscoveryServiceServer).StreamConfiguration(&grpc.GenericServerStream[DiscoveryRequest, DiscoveryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConfigurationDiscoveryService_StreamConfigurationServer = grpc.BidiStreamingServer[DiscoveryRequest, DiscoveryResponse]

func _ConfigurationDiscoveryService_ReportStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigurationDiscoveryServiceServer).ReportStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigurationDiscoveryService_ReportStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigurationDiscoveryServiceServer).ReportStatus(ctx, req.(*StatusReport))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigurationDiscoveryService_ServiceDesc is the grpc.ServiceDesc for ConfigurationDiscoveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigurationDiscoveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.control.v1.ConfigurationDiscoveryService",
	HandlerType: (*ConfigurationDiscoveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportStatus",
			Handler:    _ConfigurationDiscoveryService_ReportStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamConfiguration",
			Handler:       _ConfigurationDiscoveryService_StreamConfiguration_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "gateway/control/v1/discovery.proto",
}

const (
	DeltaDiscoveryService_DeltaStreamConfiguration_FullMethodName = "/gateway.control.v1.DeltaDiscoveryService/DeltaStreamConfiguration"
)

// DeltaDiscoveryServiceClient is the client API for DeltaDiscoveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DeltaDiscoveryService is the incremental xDS API for efficient
// configuration delivery. Unlike SotW (state-of-the-world), only
// changed resources are pushed. Data planes maintain their own
// resource state and request updates for specific resources.
//
// Protocol flow:
//  1. Data plane opens DeltaStreamConfiguration, sending a
//     DeltaDiscoveryRequest with initial resource subscriptions.
//  2. Control plane responds with a DeltaDiscoveryResponse containing
//     subscribed resources (full initial state).
//  3. On config change, control plane computes diff and pushes only
//     added/changed/removed resources.
//  4. Data plane ACKs/NACKs each response individually.
type DeltaDiscoveryServiceClient interface {
	// DeltaStreamConfiguration is the incremental-equivalent of
	// StreamConfiguration. Subscriptions are per-resource and can be
	// dynamically changed mid-stream.
	DeltaStreamConfiguration(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DeltaDiscoveryRequest, DeltaDiscoveryResponse], error)
}

type deltaDiscoveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeltaDiscoveryServiceClient(cc grpc.ClientConnInterface) DeltaDiscoveryServiceClient {
	return &deltaDiscoveryServiceClient{cc}
}

func (c *deltaDiscoveryServiceClient) DeltaStreamConfiguration(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DeltaDiscoveryRequest, DeltaDiscoveryResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DeltaDiscoveryService_ServiceDesc.Streams[0], DeltaDiscoveryService_DeltaStreamConfiguration_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DeltaDiscoveryRequest, DeltaDiscoveryResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeltaDiscoveryService_DeltaStreamConfigurationClient = grpc.BidiStreamingClient[DeltaDiscoveryRequest, DeltaDiscoveryResponse]

// DeltaDiscoveryServiceServer is the server API for DeltaDiscoveryService service.
// All implementations must embed UnimplementedDeltaDiscoveryServiceServer
// for forward compatibility.
//
// DeltaDiscoveryService is the incremental xDS API for efficient
// configuration delivery. Unlike SotW (state-of-the-world), only
// changed resources are pushed. Data planes maintain their own
// resource state and request updates for specific resources.
//
// Protocol flow:
//  1. Data plane opens DeltaStreamConfiguration, sending a
//     DeltaDiscoveryRequest with initial resource subscriptions.
//  2. Control plane responds with a DeltaDiscoveryResponse containing
//     subscribed resources (full initial state).
//  3. On config change, control plane computes diff and pushes only
//     added/changed/removed resources.
//  4. Data plane ACKs/NACKs each response individually.
type DeltaDiscoveryServiceServer interface {
	// DeltaStreamConfiguration is the incremental-equivalent of
	// StreamConfiguration. Subscriptions are per-resource and can be
	// dynamically changed mid-stream.
	DeltaStreamConfiguration(grpc.BidiStreamingServer[DeltaDiscoveryRequest, DeltaDiscoveryResponse]) error
	mustEmbedUnimplementedDeltaDiscoveryServiceServer()
}

// UnimplementedDeltaDiscoveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeltaDiscoveryServiceServer struct{}

func (UnimplementedDeltaDiscoveryServiceServer) DeltaStreamConfiguration(grpc.BidiStreamingServer[DeltaDiscoveryRequest, DeltaDiscoveryResponse]) error {
	return status.Error(codes.Unimplemented, "method DeltaStreamConfiguration not implemented")
}
func (UnimplementedDeltaDiscoveryServiceServer) mustEmbedUnimplementedDeltaDiscoveryServiceServer() {}
func (UnimplementedDeltaDiscoveryServiceServer) testEmbeddedByValue()                               {}

// UnsafeDeltaDiscoveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeltaDiscoveryServiceServer will
// result in compilation errors.
type UnsafeDeltaDiscoveryServiceServer interface {
	mustEmbedUnimplementedDeltaDiscoveryServiceServer()
}

func RegisterDeltaDiscoveryServiceServer(s grpc.ServiceRegistrar, srv DeltaDiscoveryServiceServer) {
	// If the following call panics, it indicates UnimplementedDeltaDiscoveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeltaDiscoveryService_ServiceDesc, srv)
}

func _DeltaDiscoveryService_DeltaStreamConfiguration_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DeltaDiscoveryServiceServer).DeltaStreamConfiguration(&grpc.GenericServerStream[DeltaDiscoveryRequest, DeltaDiscoveryResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DeltaDiscoveryService_DeltaStreamConfigurationServer = grpc.BidiStreamingServer[DeltaDiscoveryRequest, DeltaDiscoveryResponse]

// DeltaDiscoveryService_ServiceDesc is the grpc.ServiceDesc for DeltaDiscoveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeltaDiscoveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.control.v1.DeltaDiscoveryService",
	HandlerType: (*DeltaDiscoveryServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DeltaStreamConfiguration",
			Handler:       _DeltaDiscoveryService_DeltaStreamConfiguration_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "gateway/control/v1/discovery.proto",
}
