// Nantian Gateway xDS Discovery Service Protocol
//
// This file defines the gRPC-based xDS (discovery service) contract between
// the Go control plane and Rust data plane, including the streaming
// configuration protocol, delta (incremental) discovery, and status reporting.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: gateway/control/v1/discovery.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DiscoveryResultStatus encodes the data plane's response to a received
// ConfigSnapshot: ACK means accepted and applied, NACK means rejected.
type DiscoveryResultStatus int32

const (
	// Default unspecified value. Should not be used.
	DiscoveryResultStatus_DISCOVERY_UNSPECIFIED DiscoveryResultStatus = 0
	// The ConfigSnapshot was accepted and successfully applied.
	DiscoveryResultStatus_DISCOVERY_ACK DiscoveryResultStatus = 1
	// The ConfigSnapshot was rejected. See error_detail for the reason.
	DiscoveryResultStatus_DISCOVERY_NACK DiscoveryResultStatus = 2
)

// Enum value maps for DiscoveryResultStatus.
var (
	DiscoveryResultStatus_name = map[int32]string{
		0: "DISCOVERY_UNSPECIFIED",
		1: "DISCOVERY_ACK",
		2: "DISCOVERY_NACK",
	}
	DiscoveryResultStatus_value = map[string]int32{
		"DISCOVERY_UNSPECIFIED": 0,
		"DISCOVERY_ACK":         1,
		"DISCOVERY_NACK":        2,
	}
)

func (x DiscoveryResultStatus) Enum() *DiscoveryResultStatus {
	p := new(DiscoveryResultStatus)
	*p = x
	return p
}

func (x DiscoveryResultStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiscoveryResultStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_control_v1_discovery_proto_enumTypes[0].Descriptor()
}

func (DiscoveryResultStatus) Type() protoreflect.EnumType {
	return &file_gateway_control_v1_discovery_proto_enumTypes[0]
}

func (x DiscoveryResultStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiscoveryResultStatus.Descriptor instead.
func (DiscoveryResultStatus) EnumDescriptor() ([]byte, []int) {
	return file_gateway_control_v1_discovery_proto_rawDescGZIP(), []int{0}
}

// DeltaDiscoveryRequest carries per-resource subscription updates,
// ACK/NACK responses, and resource version tracking for incremental
// configuration delivery.
type DeltaDiscoveryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this data-plane instance (e.g. pod name).
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Kubernetes cluster name the data plane belongs to.
	Cluster string `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// --- Subscription management ---
	// Resource type URLs to subscribe to (e.g. "type.googleapis.com/gateway.control.v1.Listener").
	// Sent on initial connection and when the data plane wants to add subscriptions.
	ResourceNamesSubscribe []string `protobuf:"bytes,3,rep,name=resource_names_subscribe,json=resourceNamesSubscribe,proto3" json:"resource_names_subscribe,omitempty"`
	// Resource type URLs to unsubscribe from.
	ResourceNamesUnsubscribe []string `protobuf:"bytes,4,rep,name=resource_names_unsubscribe,json=resourceNamesUnsubscribe,proto3" json:"resource_names_unsubscribe,omitempty"`
	// --- Resource version tracking ---
	// Map from resource type URL to per-resource version strings.
	// Sent on initial connection to seed the control plane's per-client state.
	// Format: key=type_url, value=map<resource_name, version> serialized as JSON.
	InitialResourceVersions map[string]string `protobuf:"bytes,5,rep,name=initial_resource_versions,json=initialResourceVersions,proto3" json:"initial_resource_versions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// --- ACK/NACK ---
	// Nonce from the last received DeltaDiscoveryResponse, echoed back for correlation.
	ResponseNonce string `protobuf:"bytes,6,opt,name=response_nonce,json=responseNonce,proto3" json:"response_nonce,omitempty"`
	// Type URL of the resource being acknowledged/rejected.
	TypeUrl string `protobuf:"bytes,7,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	// Whether the last delta response was accepted or rejected.
	ResultStatus DiscoveryResultStatus `protobuf:"varint,8,opt,name=result_status,json=resultStatus,proto3,enum=gateway.control.v1.DiscoveryResultStatus" json:"result_status,omitempty"`
	// Human-readable error detail when result_status is NACK.
	ErrorDetail string `protobuf:"bytes,9,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
	// --- Capability negotiation ---
	// Features this data plane supports (e.g. "incremental-config", "wildcard-subscription").
	SupportedFeatures []string `protobuf:"bytes,10,rep,name=supported_features,json=supportedFeatures,proto3" json:"supported_features,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeltaDiscoveryRequest) Reset() {
	*x = DeltaDiscoveryRequest{}
	mi := &file_gateway_control_v1_discovery_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeltaDiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeltaDiscoveryRequest) ProtoMessage() {}

func (x *DeltaDiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_v1_discovery_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeltaDiscoveryRequest.ProtoReflect.Descriptor instead.
func (*DeltaDiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_gateway_control_v1_discovery_proto_rawDescGZIP(), []int{0}
}

func (x *DeltaDiscoveryRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DeltaDiscoveryRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *DeltaDiscoveryRequest) GetResourceNamesSubscribe() []string {
	if x != nil {
		return x.ResourceNamesSubscribe
	}
	return nil
}

func (x *DeltaDiscoveryRequest) GetResourceNamesUnsubscribe() []string {
	if x != nil {
		return x.ResourceNamesUnsubscribe
	}
	return nil
}

func (x *DeltaDiscoveryRequest) GetInitialResourceVersions() map[string]string {
	if x != nil {
		return x.InitialResourceVersions
	}
	return nil
}

func (x *DeltaDiscoveryRequest) GetResponseNonce() string {
	if x != nil {
		return x.ResponseNonce
	}
	return ""
}

func (x *DeltaDiscoveryRequest) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

func (x *DeltaDiscoveryRequest) GetResultStatus() DiscoveryResultStatus {
	if x != nil {
		return x.ResultStatus
	}
	return DiscoveryResultStatus_DISCOVERY_UNSPECIFIED
}

func (x *DeltaDiscoveryRequest) GetErrorDetail() string {
	if x != nil {
		return x.ErrorDetail
	}
	return ""
}

func (x *DeltaDiscoveryRequest) GetSupportedFeatures() []string {
	if x != nil {
		return x.SupportedFeatures
	}
	return nil
}

// DeltaDiscoveryResponse carries a batch of resource changes for a
// single resource type. The control plane sends one response per
// resource type that has changes.
type DeltaDiscoveryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// System version identifier (monotonically increasing).
	SystemVersionInfo string `protobuf:"bytes,1,opt,name=system_version_info,json=systemVersionInfo,proto3" json:"system_version_info,omitempty"`
	// Unique nonce for this response. The data plane echoes it back in
	// the next DeltaDiscoveryRequest for ACK/NACK correlation.
	Nonce string `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// --- Resource payload ---
	// Type URL for the resources in this response.
	TypeUrl string `protobuf:"bytes,3,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	// Resources that were added or changed since the last response.
	// Each Resource wraps the actual proto payload in google.protobuf.Any
	// and carries its own name and version.
	Resources []*Resource `protobuf:"bytes,4,rep,name=resources,proto3" json:"resources,omitempty"`
	// Names of resources that were removed (no longer present in the
	// control plane's state). The data plane should delete these from
	// its local cache.
	RemovedResources []string `protobuf:"bytes,5,rep,name=removed_resources,json=removedResources,proto3" json:"removed_resources,omitempty"`
	// --- Wildcard (non-incremental) ---
	// If true, this response replaces ALL resources of this type_url,
	// not just the changed ones. Equivalent to a SotW push for this type.
	NonIncremental bool `protobuf:"varint,6,opt,name=non_incremental,json=nonIncremental,proto3" json:"non_incremental,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeltaDiscoveryResponse) Reset() {
	*x = DeltaDiscoveryResponse{}
	mi := &file_gateway_control_v1_discovery_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeltaDiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeltaDiscoveryResponse) ProtoMessage() {}

func (x *DeltaDiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_v1_discovery_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeltaDiscoveryResponse.ProtoReflect.Descriptor instead.
func (*DeltaDiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_gateway_control_v1_discovery_proto_rawDescGZIP(), []int{1}
}

func (x *DeltaDiscoveryResponse) GetSystemVersionInfo() string {
	if x != nil {
		return x.SystemVersionInfo
	}
	return ""
}

func (x *DeltaDiscoveryResponse) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *DeltaDiscoveryResponse) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

func (x *DeltaDiscoveryResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *DeltaDiscoveryResponse) GetRemovedResources() []string {
	if x != nil {
		return x.RemovedResources
	}
	return nil
}

func (x *DeltaDiscoveryResponse) GetNonIncremental() bool {
	if x != nil {
		return x.NonIncremental
	}
	return false
}

// Resource wraps a single xDS resource with its name, version, and
// serialized payload. The payload is an opaque google.protobuf.Any
// that the data plane unmarshals based on type_url.
type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique name of this resource within its type (e.g. listener name, route name).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Version of this resource. Changes when the resource content changes.
	// Used by the control plane to compute diffs per-client.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// The actual resource payload, serialized as google.protobuf.Any.
	// The type URL in the Any matches the type_url in DeltaDiscoveryResponse.
	Resource *anypb.Any `protobuf:"bytes,3,opt,name=resource,proto3" json:"resource,omitempty"`
	// Optional alias for this resource (used for LDS→RDS indirection, etc.).
	Alias string `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`
	// Time-to-live hint. If set, the data plane should re-request this
	// resource before the TTL expires. 0 means indefinite.
	Ttl           *durationpb.Duration `protobuf:"bytes,5,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_gateway_control_v1_discovery_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_v1_discovery_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_gateway_control_v1_discovery_proto_rawDescGZIP(), []int{2}
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Resource) GetResource() *anypb.Any {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *Resource) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *Resource) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

// DiscoveryRequest is sent by the data plane when opening or updating
// a configuration stream, and after receiving a DiscoveryResponse to
// acknowledge or reject the snapshot.
type DiscoveryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this data-plane instance (e.g. pod name).
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Kubernetes cluster name the data plane belongs to.
	Cluster string `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// Last accepted configuration version, used for incremental sync.
	Version string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// Nonce from the last received DiscoveryResponse, echoed back for ACK/NACK correlation.
	Nonce string `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Resource type URLs this data-plane instance subscribes to.
	Subscriptions []string `protobuf:"bytes,5,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"`
	// Whether the last snapshot was accepted or rejected.
	ResultStatus DiscoveryResultStatus `protobuf:"varint,6,opt,name=result_status,json=resultStatus,proto3,enum=gateway.control.v1.DiscoveryResultStatus" json:"result_status,omitempty"`
	// Human-readable error detail when result_status is NACK.
	ErrorDetail string `protobuf:"bytes,7,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
	// List of optional features this data plane supports, used for
	// capability negotiation (e.g. "config-sync", "access-log-v2").
	SupportedFeatures []string `protobuf:"bytes,8,rep,name=supported_features,json=supportedFeatures,proto3" json:"supported_features,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DiscoveryRequest) Reset() {
	*x = DiscoveryRequest{}
	mi := &file_gateway_control_v1_discovery_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryRequest) ProtoMessage() {}

func (x *DiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_v1_discovery_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryRequest.ProtoReflect.Descriptor instead.
func (*DiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_gateway_control_v1_discovery_proto_rawDescGZIP(), []int{3}
}

func (x *DiscoveryRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DiscoveryRequest) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *DiscoveryRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DiscoveryRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *DiscoveryRequest) GetSubscriptions() []string {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

func (x *DiscoveryRequest) GetResultStatus() DiscoveryResultStatus {
	if x != nil {
		return x.ResultStatus
	}
	return DiscoveryResultStatus_DISCOVERY_UNSPECIFIED
}

func (x *DiscoveryRequest) GetErrorDetail() string {
	if x != nil {
		return x.ErrorDetail
	}
	return ""
}

func (x *DiscoveryRequest) GetSupportedFeatures() []string {
	if x != nil {
		return x.SupportedFeatures
	}
	return nil
}

// DiscoveryResponse is sent by the control plane in reply to a
// DiscoveryRequest, carrying a full ConfigSnapshot.
type DiscoveryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Configuration version identifier. Incremented on every snapshot change.
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// Unique nonce for this response. The data plane echoes it back in the
	// next DiscoveryRequest for ACK/NACK correlation.
	Nonce string `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// The complete configuration snapshot.
	Snapshot      *ConfigSnapshot `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DiscoveryResponse) Reset() {
	*x = DiscoveryResponse{}
	mi := &file_gateway_control_v1_discovery_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryResponse) ProtoMessage() {}

func (x *DiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_v1_discovery_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryResponse.ProtoReflect.Descriptor instead.
func (*DiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_gateway_control_v1_discovery_proto_rawDescGZIP(), []int{4}
}

func (x *DiscoveryResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DiscoveryResponse) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *DiscoveryResponse) GetSnapshot() *ConfigSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// StatusReport is sent periodically by the data plane to inform the
// control plane of its current health and readiness.
type StatusReport struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this data-plane instance.
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Currently applied configuration version.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Whether the data plane is ready to serve traffic.
	Ready bool `protobuf:"varint,3,opt,name=ready,proto3" json:"ready,omitempty"`
	// Human-readable status message (e.g. "healthy", "degraded: no backends").
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// Timestamp when this status was observed.
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusReport) Reset() {
	*x = StatusReport{}
	mi := &file_gateway_control_v1_discovery_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReport) ProtoMessage() {}

func (x *StatusReport) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_v1_discovery_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReport.ProtoReflect.Descriptor instead.
func (*StatusReport) Descriptor() ([]byte, []int) {
	return file_gateway_control_v1_discovery_proto_rawDescGZIP(), []int{5}
}

func (x *StatusReport) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StatusReport) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StatusReport) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *StatusReport) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StatusReport) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

// StatusAck is the control plane's acknowledgement of a StatusReport.
// It confirms receipt and optionally carries back instructions to the
// data plane (future: e.g. "reload", "drain", "shutdown").
type StatusAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the status report was received and processed successfully.
	Accepted      bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusAck) Reset() {
	*x = StatusAck{}
	mi := &file_gateway_control_v1_discovery_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusAck) ProtoMessage() {}

func (x *StatusAck) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_v1_discovery_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusAck.ProtoReflect.Descriptor instead.
func (*StatusAck) Descriptor() ([]byte, []int) {
	return file_gateway_control_v1_discovery_proto_rawDescGZIP(), []int{6}
}

func (x *StatusAck) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_gateway_control_v1_discovery_proto protoreflect.FileDescriptor

const file_gateway_control_v1_discovery_proto_rawDesc = "" +
	"\n" +
	"\"gateway/control/v1/discovery.proto\x12\x12gateway.control.v1\x1a\x1fgateway/control/v1/config.proto\x1a\x19google/protobuf/any.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf7\x04\n" +
	"\x15DeltaDiscoveryRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\acluster\x18\x02 \x01(\tR\acluster\x128\n" +
	"\x18resource_names_subscribe\x18\x03 \x03(\tR\x16resourceNamesSubscribe\x12<\n" +
	"\x1aresource_names_unsubscribe\x18\x04 \x03(\tR\x18resourceNamesUnsubscribe\x12\x82\x01\n" +
	"\x19initial_resource_versions\x18\x05 \x03(\v2F.gateway.control.v1.DeltaDiscoveryRequest.InitialResourceVersionsEntryR\x17initialResourceVersions\x12%\n" +
	"\x0eresponse_nonce\x18\x06 \x01(\tR\rresponseNonce\x12\x19\n" +
	"\btype_url\x18\a \x01(\tR\atypeUrl\x12N\n" +
	"\rresult_status\x18\b \x01(\x0e2).gateway.control.v1.DiscoveryResultStatusR\fresultStatus\x12!\n" +
	"\ferror_detail\x18\t \x01(\tR\verrorDetail\x12-\n" +
	"\x12supported_features\x18\n" +
	" \x03(\tR\x11supportedFeatures\x1aJ\n" +
	"\x1cInitialResourceVersionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8b\x02\n" +
	"\x16DeltaDiscoveryResponse\x12.\n" +
	"\x13system_version_info\x18\x01 \x01(\tR\x11systemVersionInfo\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\tR\x05nonce\x12\x19\n" +
	"\btype_url\x18\x03 \x01(\tR\atypeUrl\x12:\n" +
	"\tresources\x18\x04 \x03(\v2\x1c.gateway.control.v1.ResourceR\tresources\x12+\n" +
	"\x11removed_resources\x18\x05 \x03(\tR\x10removedResources\x12'\n" +
	"\x0fnon_incremental\x18\x06 \x01(\bR\x0enonIncremental\"\xad\x01\n" +
	"\bResource\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x120\n" +
	"\bresource\x18\x03 \x01(\v2\x14.google.protobuf.AnyR\bresource\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias\x12+\n" +
	"\x03ttl\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\"\xbd\x02\n" +
	"\x10DiscoveryRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\acluster\x18\x02 \x01(\tR\acluster\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x14\n" +
	"\x05nonce\x18\x04 \x01(\tR\x05nonce\x12$\n" +
	"\rsubscriptions\x18\x05 \x03(\tR\rsubscriptions\x12N\n" +
	"\rresult_status\x18\x06 \x01(\x0e2).gateway.control.v1.DiscoveryResultStatusR\fresultStatus\x12!\n" +
	"\ferror_detail\x18\a \x01(\tR\verrorDetail\x12-\n" +
	"\x12supported_features\x18\b \x03(\tR\x11supportedFeatures\"\x83\x01\n" +
	"\x11DiscoveryResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\tR\x05nonce\x12>\n" +
	"\bsnapshot\x18\x03 \x01(\v2\".gateway.control.v1.ConfigSnapshotR\bsnapshot\"\xae\x01\n" +
	"\fStatusReport\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x14\n" +
	"\x05ready\x18\x03 \x01(\bR\x05ready\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12;\n" +
	"\vobserved_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\"'\n" +
	"\tStatusAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted*Y\n" +
	"\x15DiscoveryResultStatus\x12\x19\n" +
	"\x15DISCOVERY_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rDISCOVERY_ACK\x10\x01\x12\x12\n" +
	"\x0eDISCOVERY_NACK\x10\x022\xd8\x01\n" +
	"\x1dConfigurationDiscoveryService\x12f\n" +
	"\x13StreamConfiguration\x12$.gateway.control.v1.DiscoveryRequest\x1a%.gateway.control.v1.DiscoveryResponse(\x010\x01\x12O\n" +
	"\fReportStatus\x12 .gateway.control.v1.StatusReport\x1a\x1d.gateway.control.v1.StatusAck2\x8e\x01\n" +
	"\x15DeltaDiscoveryService\x12u\n" +
	"\x18DeltaStreamConfiguration\x12).gateway.control.v1.DeltaDiscoveryRequest\x1a*.gateway.control.v1.DeltaDiscoveryResponse(\x010\x01B:Z8github.com/nantian-gw/proto/gateway/control/v1;controlv1b\x06proto3"

var (
	file_gateway_control_v1_discovery_proto_rawDescOnce sync.Once
	file_gateway_control_v1_discovery_proto_rawDescData []byte
)

func file_gateway_control_v1_discovery_proto_rawDescGZIP() []byte {
	file_gateway_control_v1_discovery_proto_rawDescOnce.Do(func() {
		file_gateway_control_v1_discovery_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_control_v1_discovery_proto_rawDesc), len(file_gateway_control_v1_discovery_proto_rawDesc)))
	})
	return file_gateway_control_v1_discovery_proto_rawDescData
}

var file_gateway_control_v1_discovery_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_gateway_control_v1_discovery_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_gateway_control_v1_discovery_proto_goTypes = []any{
	(DiscoveryResultStatus)(0),     // 0: gateway.control.v1.DiscoveryResultStatus
	(*DeltaDiscoveryRequest)(nil),  // 1: gateway.control.v1.DeltaDiscoveryRequest
	(*DeltaDiscoveryResponse)(nil), // 2: gateway.control.v1.DeltaDiscoveryResponse
	(*Resource)(nil),               // 3: gateway.control.v1.Resource
	(*DiscoveryRequest)(nil),       // 4: gateway.control.v1.DiscoveryRequest
	(*DiscoveryResponse)(nil),      // 5: gateway.control.v1.DiscoveryResponse
	(*StatusReport)(nil),           // 6: gateway.control.v1.StatusReport
	(*StatusAck)(nil),              // 7: gateway.control.v1.StatusAck
	nil,                            // 8: gateway.control.v1.DeltaDiscoveryRequest.InitialResourceVersionsEntry
	(*anypb.Any)(nil),              // 9: google.protobuf.Any
	(*durationpb.Duration)(nil),    // 10: google.protobuf.Duration
	(*ConfigSnapshot)(nil),         // 11: gateway.control.v1.ConfigSnapshot
	(*timestamppb.Timestamp)(nil),  // 12: google.protobuf.Timestamp
}
var file_gateway_control_v1_discovery_proto_depIdxs = []int32{
	8,  // 0: gateway.control.v1.DeltaDiscoveryRequest.initial_resource_versions:type_name -> gateway.control.v1.DeltaDiscoveryRequest.InitialResourceVersionsEntry
	0,  // 1: gateway.control.v1.DeltaDiscoveryRequest.result_status:type_name -> gateway.control.v1.DiscoveryResultStatus
	3,  // 2: gateway.control.v1.DeltaDiscoveryResponse.resources:type_name -> gateway.control.v1.Resource
	9,  // 3: gateway.control.v1.Resource.resource:type_name -> google.protobuf.Any
	10, // 4: gateway.control.v1.Resource.ttl:type_name -> google.protobuf.Duration
	0,  // 5: gateway.control.v1.DiscoveryRequest.result_status:type_name -> gateway.control.v1.DiscoveryResultStatus
	11, // 6: gateway.control.v1.DiscoveryResponse.snapshot:type_name -> gateway.control.v1.ConfigSnapshot
	12, // 7: gateway.control.v1.StatusReport.observed_at:type_name -> google.protobuf.Timestamp
	4,  // 8: gateway.control.v1.ConfigurationDiscoveryService.StreamConfiguration:input_type -> gateway.control.v1.DiscoveryRequest
	6,  // 9: gateway.control.v1.ConfigurationDiscoveryService.ReportStatus:input_type -> gateway.control.v1.StatusReport
	1,  // 10: gateway.control.v1.DeltaDiscoveryService.DeltaStreamConfiguration:input_type -> gateway.control.v1.DeltaDiscoveryRequest
	5,  // 11: gateway.control.v1.ConfigurationDiscoveryService.StreamConfiguration:output_type -> gateway.control.v1.DiscoveryResponse
	7,  // 12: gateway.control.v1.ConfigurationDiscoveryService.ReportStatus:output_type -> gateway.control.v1.StatusAck
	2,  // 13: gateway.control.v1.DeltaDiscoveryService.DeltaStreamConfiguration:output_type -> gateway.control.v1.DeltaDiscoveryResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_gateway_control_v1_discovery_proto_init() }
func file_gateway_control_v1_discovery_proto_init() {
	if File_gateway_control_v1_discovery_proto != nil {
		return
	}
	file_gateway_control_v1_config_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_control_v1_discovery_proto_rawDesc), len(file_gateway_control_v1_discovery_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_gateway_control_v1_discovery_proto_goTypes,
		DependencyIndexes: file_gateway_control_v1_discovery_proto_depIdxs,
		EnumInfos:         file_gateway_control_v1_discovery_proto_enumTypes,
		MessageInfos:      file_gateway_control_v1_discovery_proto_msgTypes,
	}.Build()
	File_gateway_control_v1_discovery_proto = out.File
	file_gateway_control_v1_discovery_proto_goTypes = nil
	file_gateway_control_v1_discovery_proto_depIdxs = nil
}
