// Nantian Gateway Route Policy Configuration
//
// This file defines per-route policy overrides for timeout, body size,
// proxy buffering, and connection keepalive settings.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: gateway/control/v1/route_policy.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RoutePolicy provides per-route overrides for timeout, body size,
// proxy buffering, and connection keepalive settings. When attached
// to an HttpRoute or GrpcRoute, fields set here override the
// dataplane global defaults for that route.
type RoutePolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Per-route timeout overrides for request, backend, and connection timeouts.
	Timeout *RoutePolicyTimeout `protobuf:"bytes,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// Per-route body and header size limits.
	BodyLimit *RoutePolicyBodyLimit `protobuf:"bytes,2,opt,name=body_limit,json=bodyLimit,proto3" json:"body_limit,omitempty"`
	// Per-route proxy buffering configuration.
	Proxy *RoutePolicyProxy `protobuf:"bytes,3,opt,name=proxy,proto3" json:"proxy,omitempty"`
	// Per-route connection keepalive settings for client and upstream connections.
	Connection    *RoutePolicyConnection `protobuf:"bytes,4,opt,name=connection,proto3" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutePolicy) Reset() {
	*x = RoutePolicy{}
	mi := &file_gateway_control_v1_route_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePolicy) ProtoMessage() {}

func (x *RoutePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_v1_route_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutePolicy.ProtoReflect.Descriptor instead.
func (*RoutePolicy) Descriptor() ([]byte, []int) {
	return file_gateway_control_v1_route_policy_proto_rawDescGZIP(), []int{0}
}

func (x *RoutePolicy) GetTimeout() *RoutePolicyTimeout {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *RoutePolicy) GetBodyLimit() *RoutePolicyBodyLimit {
	if x != nil {
		return x.BodyLimit
	}
	return nil
}

func (x *RoutePolicy) GetProxy() *RoutePolicyProxy {
	if x != nil {
		return x.Proxy
	}
	return nil
}

func (x *RoutePolicy) GetConnection() *RoutePolicyConnection {
	if x != nil {
		return x.Connection
	}
	return nil
}

// RoutePolicyTimeout specifies per-route timeout values that override
// the dataplane global timeout defaults.
type RoutePolicyTimeout struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum duration for the entire request-response cycle (from first byte received to last byte sent).
	Request *durationpb.Duration `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	// Maximum duration for a single backend request attempt (a single upstream connection).
	BackendRequest *durationpb.Duration `protobuf:"bytes,2,opt,name=backend_request,json=backendRequest,proto3" json:"backend_request,omitempty"`
	// Maximum duration to establish a TCP connection to the backend.
	Connect *durationpb.Duration `protobuf:"bytes,3,opt,name=connect,proto3" json:"connect,omitempty"`
	// Maximum duration spent finding a viable upstream backend during retries.
	NextUpstream  *durationpb.Duration `protobuf:"bytes,4,opt,name=next_upstream,json=nextUpstream,proto3" json:"next_upstream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutePolicyTimeout) Reset() {
	*x = RoutePolicyTimeout{}
	mi := &file_gateway_control_v1_route_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutePolicyTimeout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePolicyTimeout) ProtoMessage() {}

func (x *RoutePolicyTimeout) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_v1_route_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutePolicyTimeout.ProtoReflect.Descriptor instead.
func (*RoutePolicyTimeout) Descriptor() ([]byte, []int) {
	return file_gateway_control_v1_route_policy_proto_rawDescGZIP(), []int{1}
}

func (x *RoutePolicyTimeout) GetRequest() *durationpb.Duration {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *RoutePolicyTimeout) GetBackendRequest() *durationpb.Duration {
	if x != nil {
		return x.BackendRequest
	}
	return nil
}

func (x *RoutePolicyTimeout) GetConnect() *durationpb.Duration {
	if x != nil {
		return x.Connect
	}
	return nil
}

func (x *RoutePolicyTimeout) GetNextUpstream() *durationpb.Duration {
	if x != nil {
		return x.NextUpstream
	}
	return nil
}

// RoutePolicyBodyLimit restricts request body and header sizes on a per-route basis.
type RoutePolicyBodyLimit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum request body size in bytes. Requests exceeding this receive HTTP 413 (Payload Too Large).
	MaxRequestBodyBytes uint64 `protobuf:"varint,1,opt,name=max_request_body_bytes,json=maxRequestBodyBytes,proto3" json:"max_request_body_bytes,omitempty"`
	// Size of the buffer used to read the request body before writing to a temporary file.
	RequestBodyBufferBytes uint64 `protobuf:"varint,2,opt,name=request_body_buffer_bytes,json=requestBodyBufferBytes,proto3" json:"request_body_buffer_bytes,omitempty"`
	// Maximum combined size of all request headers in bytes.
	MaxRequestHeaderBytes uint64 `protobuf:"varint,3,opt,name=max_request_header_bytes,json=maxRequestHeaderBytes,proto3" json:"max_request_header_bytes,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RoutePolicyBodyLimit) Reset() {
	*x = RoutePolicyBodyLimit{}
	mi := &file_gateway_control_v1_route_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutePolicyBodyLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePolicyBodyLimit) ProtoMessage() {}

func (x *RoutePolicyBodyLimit) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_v1_route_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutePolicyBodyLimit.ProtoReflect.Descriptor instead.
func (*RoutePolicyBodyLimit) Descriptor() ([]byte, []int) {
	return file_gateway_control_v1_route_policy_proto_rawDescGZIP(), []int{2}
}

func (x *RoutePolicyBodyLimit) GetMaxRequestBodyBytes() uint64 {
	if x != nil {
		return x.MaxRequestBodyBytes
	}
	return 0
}

func (x *RoutePolicyBodyLimit) GetRequestBodyBufferBytes() uint64 {
	if x != nil {
		return x.RequestBodyBufferBytes
	}
	return 0
}

func (x *RoutePolicyBodyLimit) GetMaxRequestHeaderBytes() uint64 {
	if x != nil {
		return x.MaxRequestHeaderBytes
	}
	return 0
}

// RoutePolicyProxy controls HTTP proxy buffering behavior on a per-route basis.
type RoutePolicyProxy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If true, buffer the entire client request body before proxying to the backend.
	RequestBuffering *wrapperspb.BoolValue `protobuf:"bytes,1,opt,name=request_buffering,json=requestBuffering,proto3" json:"request_buffering,omitempty"`
	// If true, buffer the backend response before sending to the client. If false, stream the response.
	ResponseBuffering *wrapperspb.BoolValue `protobuf:"bytes,2,opt,name=response_buffering,json=responseBuffering,proto3" json:"response_buffering,omitempty"`
	// Size of each response buffer in bytes (used when response_buffering is enabled).
	BufferSize uint64 `protobuf:"varint,3,opt,name=buffer_size,json=bufferSize,proto3" json:"buffer_size,omitempty"`
	// Number of response buffers to allocate (used when response_buffering is enabled).
	BufferCount   uint32 `protobuf:"varint,4,opt,name=buffer_count,json=bufferCount,proto3" json:"buffer_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoutePolicyProxy) Reset() {
	*x = RoutePolicyProxy{}
	mi := &file_gateway_control_v1_route_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutePolicyProxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePolicyProxy) ProtoMessage() {}

func (x *RoutePolicyProxy) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_v1_route_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutePolicyProxy.ProtoReflect.Descriptor instead.
func (*RoutePolicyProxy) Descriptor() ([]byte, []int) {
	return file_gateway_control_v1_route_policy_proto_rawDescGZIP(), []int{3}
}

func (x *RoutePolicyProxy) GetRequestBuffering() *wrapperspb.BoolValue {
	if x != nil {
		return x.RequestBuffering
	}
	return nil
}

func (x *RoutePolicyProxy) GetResponseBuffering() *wrapperspb.BoolValue {
	if x != nil {
		return x.ResponseBuffering
	}
	return nil
}

func (x *RoutePolicyProxy) GetBufferSize() uint64 {
	if x != nil {
		return x.BufferSize
	}
	return 0
}

func (x *RoutePolicyProxy) GetBufferCount() uint32 {
	if x != nil {
		return x.BufferCount
	}
	return 0
}

// RoutePolicyConnection controls keepalive behavior for client-facing and
// upstream connections on a per-route basis.
type RoutePolicyConnection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of requests allowed on a single keepalive client connection.
	KeepaliveRequests uint32 `protobuf:"varint,1,opt,name=keepalive_requests,json=keepaliveRequests,proto3" json:"keepalive_requests,omitempty"`
	// Maximum lifetime of a keepalive client connection.
	KeepaliveTime *durationpb.Duration `protobuf:"bytes,2,opt,name=keepalive_time,json=keepaliveTime,proto3" json:"keepalive_time,omitempty"`
	// Maximum idle time before closing a keepalive client connection.
	KeepaliveTimeout *durationpb.Duration `protobuf:"bytes,3,opt,name=keepalive_timeout,json=keepaliveTimeout,proto3" json:"keepalive_timeout,omitempty"`
	// Maximum number of idle upstream keepalive connections to maintain in the pool.
	UpstreamKeepalivePoolSize uint32 `protobuf:"varint,4,opt,name=upstream_keepalive_pool_size,json=upstreamKeepalivePoolSize,proto3" json:"upstream_keepalive_pool_size,omitempty"`
	// Maximum idle time before closing an upstream keepalive connection.
	UpstreamKeepaliveIdle *durationpb.Duration `protobuf:"bytes,5,opt,name=upstream_keepalive_idle,json=upstreamKeepaliveIdle,proto3" json:"upstream_keepalive_idle,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RoutePolicyConnection) Reset() {
	*x = RoutePolicyConnection{}
	mi := &file_gateway_control_v1_route_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoutePolicyConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoutePolicyConnection) ProtoMessage() {}

func (x *RoutePolicyConnection) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_v1_route_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoutePolicyConnection.ProtoReflect.Descriptor instead.
func (*RoutePolicyConnection) Descriptor() ([]byte, []int) {
	return file_gateway_control_v1_route_policy_proto_rawDescGZIP(), []int{4}
}

func (x *RoutePolicyConnection) GetKeepaliveRequests() uint32 {
	if x != nil {
		return x.KeepaliveRequests
	}
	return 0
}

func (x *RoutePolicyConnection) GetKeepaliveTime() *durationpb.Duration {
	if x != nil {
		return x.KeepaliveTime
	}
	return nil
}

func (x *RoutePolicyConnection) GetKeepaliveTimeout() *durationpb.Duration {
	if x != nil {
		return x.KeepaliveTimeout
	}
	return nil
}

func (x *RoutePolicyConnection) GetUpstreamKeepalivePoolSize() uint32 {
	if x != nil {
		return x.UpstreamKeepalivePoolSize
	}
	return 0
}

func (x *RoutePolicyConnection) GetUpstreamKeepaliveIdle() *durationpb.Duration {
	if x != nil {
		return x.UpstreamKeepaliveIdle
	}
	return nil
}

var File_gateway_control_v1_route_policy_proto protoreflect.FileDescriptor

const file_gateway_control_v1_route_policy_proto_rawDesc = "" +
	"\n" +
	"%gateway/control/v1/route_policy.proto\x12\x12gateway.control.v1\x1a\x1egoogle/protobuf/duration.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x9f\x02\n" +
	"\vRoutePolicy\x12@\n" +
	"\atimeout\x18\x01 \x01(\v2&.gateway.control.v1.RoutePolicyTimeoutR\atimeout\x12G\n" +
	"\n" +
	"body_limit\x18\x02 \x01(\v2(.gateway.control.v1.RoutePolicyBodyLimitR\tbodyLimit\x12:\n" +
	"\x05proxy\x18\x03 \x01(\v2$.gateway.control.v1.RoutePolicyProxyR\x05proxy\x12I\n" +
	"\n" +
	"connection\x18\x04 \x01(\v2).gateway.control.v1.RoutePolicyConnectionR\n" +
	"connection\"\x82\x02\n" +
	"\x12RoutePolicyTimeout\x123\n" +
	"\arequest\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\arequest\x12B\n" +
	"\x0fbackend_request\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x0ebackendRequest\x123\n" +
	"\aconnect\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\aconnect\x12>\n" +
	"\rnext_upstream\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\fnextUpstream\"\xbf\x01\n" +
	"\x14RoutePolicyBodyLimit\x123\n" +
	"\x16max_request_body_bytes\x18\x01 \x01(\x04R\x13maxRequestBodyBytes\x129\n" +
	"\x19request_body_buffer_bytes\x18\x02 \x01(\x04R\x16requestBodyBufferBytes\x127\n" +
	"\x18max_request_header_bytes\x18\x03 \x01(\x04R\x15maxRequestHeaderBytes\"\xea\x01\n" +
	"\x10RoutePolicyProxy\x12G\n" +
	"\x11request_buffering\x18\x01 \x01(\v2\x1a.google.protobuf.BoolValueR\x10requestBuffering\x12I\n" +
	"\x12response_buffering\x18\x02 \x01(\v2\x1a.google.protobuf.BoolValueR\x11responseBuffering\x12\x1f\n" +
	"\vbuffer_size\x18\x03 \x01(\x04R\n" +
	"bufferSize\x12!\n" +
	"\fbuffer_count\x18\x04 \x01(\rR\vbufferCount\"\xe4\x02\n" +
	"\x15RoutePolicyConnection\x12-\n" +
	"\x12keepalive_requests\x18\x01 \x01(\rR\x11keepaliveRequests\x12@\n" +
	"\x0ekeepalive_time\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\rkeepaliveTime\x12F\n" +
	"\x11keepalive_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x10keepaliveTimeout\x12?\n" +
	"\x1cupstream_keepalive_pool_size\x18\x04 \x01(\rR\x19upstreamKeepalivePoolSize\x12Q\n" +
	"\x17upstream_keepalive_idle\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x15upstreamKeepaliveIdleB:Z8github.com/nantian-gw/proto/gateway/control/v1;controlv1b\x06proto3"

var (
	file_gateway_control_v1_route_policy_proto_rawDescOnce sync.Once
	file_gateway_control_v1_route_policy_proto_rawDescData []byte
)

func file_gateway_control_v1_route_policy_proto_rawDescGZIP() []byte {
	file_gateway_control_v1_route_policy_proto_rawDescOnce.Do(func() {
		file_gateway_control_v1_route_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_control_v1_route_policy_proto_rawDesc), len(file_gateway_control_v1_route_policy_proto_rawDesc)))
	})
	return file_gateway_control_v1_route_policy_proto_rawDescData
}

var file_gateway_control_v1_route_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_gateway_control_v1_route_policy_proto_goTypes = []any{
	(*RoutePolicy)(nil),           // 0: gateway.control.v1.RoutePolicy
	(*RoutePolicyTimeout)(nil),    // 1: gateway.control.v1.RoutePolicyTimeout
	(*RoutePolicyBodyLimit)(nil),  // 2: gateway.control.v1.RoutePolicyBodyLimit
	(*RoutePolicyProxy)(nil),      // 3: gateway.control.v1.RoutePolicyProxy
	(*RoutePolicyConnection)(nil), // 4: gateway.control.v1.RoutePolicyConnection
	(*durationpb.Duration)(nil),   // 5: google.protobuf.Duration
	(*wrapperspb.BoolValue)(nil),  // 6: google.protobuf.BoolValue
}
var file_gateway_control_v1_route_policy_proto_depIdxs = []int32{
	1,  // 0: gateway.control.v1.RoutePolicy.timeout:type_name -> gateway.control.v1.RoutePolicyTimeout
	2,  // 1: gateway.control.v1.RoutePolicy.body_limit:type_name -> gateway.control.v1.RoutePolicyBodyLimit
	3,  // 2: gateway.control.v1.RoutePolicy.proxy:type_name -> gateway.control.v1.RoutePolicyProxy
	4,  // 3: gateway.control.v1.RoutePolicy.connection:type_name -> gateway.control.v1.RoutePolicyConnection
	5,  // 4: gateway.control.v1.RoutePolicyTimeout.request:type_name -> google.protobuf.Duration
	5,  // 5: gateway.control.v1.RoutePolicyTimeout.backend_request:type_name -> google.protobuf.Duration
	5,  // 6: gateway.control.v1.RoutePolicyTimeout.connect:type_name -> google.protobuf.Duration
	5,  // 7: gateway.control.v1.RoutePolicyTimeout.next_upstream:type_name -> google.protobuf.Duration
	6,  // 8: gateway.control.v1.RoutePolicyProxy.request_buffering:type_name -> google.protobuf.BoolValue
	6,  // 9: gateway.control.v1.RoutePolicyProxy.response_buffering:type_name -> google.protobuf.BoolValue
	5,  // 10: gateway.control.v1.RoutePolicyConnection.keepalive_time:type_name -> google.protobuf.Duration
	5,  // 11: gateway.control.v1.RoutePolicyConnection.keepalive_timeout:type_name -> google.protobuf.Duration
	5,  // 12: gateway.control.v1.RoutePolicyConnection.upstream_keepalive_idle:type_name -> google.protobuf.Duration
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_gateway_control_v1_route_policy_proto_init() }
func file_gateway_control_v1_route_policy_proto_init() {
	if File_gateway_control_v1_route_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_control_v1_route_policy_proto_rawDesc), len(file_gateway_control_v1_route_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_control_v1_route_policy_proto_goTypes,
		DependencyIndexes: file_gateway_control_v1_route_policy_proto_depIdxs,
		MessageInfos:      file_gateway_control_v1_route_policy_proto_msgTypes,
	}.Build()
	File_gateway_control_v1_route_policy_proto = out.File
	file_gateway_control_v1_route_policy_proto_goTypes = nil
	file_gateway_control_v1_route_policy_proto_depIdxs = nil
}
