// Nantian Gateway WebAssembly Plugin Configuration
//
// This file defines WebAssembly plugin configuration types for the
// data plane to load and execute Wasm modules at specified hook points.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: gateway/control/v1/wasm.proto

package controlv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WasmPluginConfig describes a WebAssembly plugin to be loaded and executed
// by the data plane at specified hook points.
type WasmPluginConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plugin name (matches the Kubernetes WasmPlugin resource name).
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Kubernetes namespace of the plugin resource.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Compiled WebAssembly module bytes.
	WasmBytes []byte `protobuf:"bytes,3,opt,name=wasm_bytes,json=wasmBytes,proto3" json:"wasm_bytes,omitempty"`
	// SHA-256 hash of the Wasm module for integrity verification.
	Sha256 string `protobuf:"bytes,4,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// Hook points where this plugin executes (e.g. "http-request-headers",
	// "http-response-body", "grpc-request").
	Hooks []string `protobuf:"bytes,5,rep,name=hooks,proto3" json:"hooks,omitempty"`
	// JSON configuration passed to the plugin at initialization.
	ConfigJson string `protobuf:"bytes,6,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	// Sandbox constraints for Wasm execution.
	Sandbox *WasmSandboxConfig `protobuf:"bytes,7,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	// bytes instead of inlining them in `wasm_bytes`. When both are set,
	// `wasm_bytes` takes precedence.
	SourceUrl     string `protobuf:"bytes,8,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WasmPluginConfig) Reset() {
	*x = WasmPluginConfig{}
	mi := &file_gateway_control_v1_wasm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WasmPluginConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WasmPluginConfig) ProtoMessage() {}

func (x *WasmPluginConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_v1_wasm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WasmPluginConfig.ProtoReflect.Descriptor instead.
func (*WasmPluginConfig) Descriptor() ([]byte, []int) {
	return file_gateway_control_v1_wasm_proto_rawDescGZIP(), []int{0}
}

func (x *WasmPluginConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WasmPluginConfig) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WasmPluginConfig) GetWasmBytes() []byte {
	if x != nil {
		return x.WasmBytes
	}
	return nil
}

func (x *WasmPluginConfig) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *WasmPluginConfig) GetHooks() []string {
	if x != nil {
		return x.Hooks
	}
	return nil
}

func (x *WasmPluginConfig) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *WasmPluginConfig) GetSandbox() *WasmSandboxConfig {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

func (x *WasmPluginConfig) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

// WasmSandboxConfig defines resource limits and security constraints
// for WebAssembly plugin execution.
type WasmSandboxConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum memory the Wasm module can allocate, in bytes.
	MaxMemoryBytes uint64 `protobuf:"varint,1,opt,name=max_memory_bytes,json=maxMemoryBytes,proto3" json:"max_memory_bytes,omitempty"`
	// Maximum execution time per hook invocation, in milliseconds.
	MaxExecutionTimeMs uint64 `protobuf:"varint,2,opt,name=max_execution_time_ms,json=maxExecutionTimeMs,proto3" json:"max_execution_time_ms,omitempty"`
	// Whether the plugin can make outbound network requests.
	AllowNetwork bool `protobuf:"varint,3,opt,name=allow_network,json=allowNetwork,proto3" json:"allow_network,omitempty"`
	// Whether the plugin can access the host file system.
	AllowFileSystem bool `protobuf:"varint,4,opt,name=allow_file_system,json=allowFileSystem,proto3" json:"allow_file_system,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WasmSandboxConfig) Reset() {
	*x = WasmSandboxConfig{}
	mi := &file_gateway_control_v1_wasm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WasmSandboxConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WasmSandboxConfig) ProtoMessage() {}

func (x *WasmSandboxConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_control_v1_wasm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WasmSandboxConfig.ProtoReflect.Descriptor instead.
func (*WasmSandboxConfig) Descriptor() ([]byte, []int) {
	return file_gateway_control_v1_wasm_proto_rawDescGZIP(), []int{1}
}

func (x *WasmSandboxConfig) GetMaxMemoryBytes() uint64 {
	if x != nil {
		return x.MaxMemoryBytes
	}
	return 0
}

func (x *WasmSandboxConfig) GetMaxExecutionTimeMs() uint64 {
	if x != nil {
		return x.MaxExecutionTimeMs
	}
	return 0
}

func (x *WasmSandboxConfig) GetAllowNetwork() bool {
	if x != nil {
		return x.AllowNetwork
	}
	return false
}

func (x *WasmSandboxConfig) GetAllowFileSystem() bool {
	if x != nil {
		return x.AllowFileSystem
	}
	return false
}

var File_gateway_control_v1_wasm_proto protoreflect.FileDescriptor

const file_gateway_control_v1_wasm_proto_rawDesc = "" +
	"\n" +
	"\x1dgateway/control/v1/wasm.proto\x12\x12gateway.control.v1\"\x92\x02\n" +
	"\x10WasmPluginConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"wasm_bytes\x18\x03 \x01(\fR\twasmBytes\x12\x16\n" +
	"\x06sha256\x18\x04 \x01(\tR\x06sha256\x12\x14\n" +
	"\x05hooks\x18\x05 \x03(\tR\x05hooks\x12\x1f\n" +
	"\vconfig_json\x18\x06 \x01(\tR\n" +
	"configJson\x12?\n" +
	"\asandbox\x18\a \x01(\v2%.gateway.control.v1.WasmSandboxConfigR\asandbox\x12\x1d\n" +
	"\n" +
	"source_url\x18\b \x01(\tR\tsourceUrl\"\xc1\x01\n" +
	"\x11WasmSandboxConfig\x12(\n" +
	"\x10max_memory_bytes\x18\x01 \x01(\x04R\x0emaxMemoryBytes\x121\n" +
	"\x15max_execution_time_ms\x18\x02 \x01(\x04R\x12maxExecutionTimeMs\x12#\n" +
	"\rallow_network\x18\x03 \x01(\bR\fallowNetwork\x12*\n" +
	"\x11allow_file_system\x18\x04 \x01(\bR\x0fallowFileSystemB:Z8github.com/nantian-gw/proto/gateway/control/v1;controlv1b\x06proto3"

var (
	file_gateway_control_v1_wasm_proto_rawDescOnce sync.Once
	file_gateway_control_v1_wasm_proto_rawDescData []byte
)

func file_gateway_control_v1_wasm_proto_rawDescGZIP() []byte {
	file_gateway_control_v1_wasm_proto_rawDescOnce.Do(func() {
		file_gateway_control_v1_wasm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_control_v1_wasm_proto_rawDesc), len(file_gateway_control_v1_wasm_proto_rawDesc)))
	})
	return file_gateway_control_v1_wasm_proto_rawDescData
}

var file_gateway_control_v1_wasm_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_gateway_control_v1_wasm_proto_goTypes = []any{
	(*WasmPluginConfig)(nil),  // 0: gateway.control.v1.WasmPluginConfig
	(*WasmSandboxConfig)(nil), // 1: gateway.control.v1.WasmSandboxConfig
}
var file_gateway_control_v1_wasm_proto_depIdxs = []int32{
	1, // 0: gateway.control.v1.WasmPluginConfig.sandbox:type_name -> gateway.control.v1.WasmSandboxConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_gateway_control_v1_wasm_proto_init() }
func file_gateway_control_v1_wasm_proto_init() {
	if File_gateway_control_v1_wasm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_control_v1_wasm_proto_rawDesc), len(file_gateway_control_v1_wasm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gateway_control_v1_wasm_proto_goTypes,
		DependencyIndexes: file_gateway_control_v1_wasm_proto_depIdxs,
		MessageInfos:      file_gateway_control_v1_wasm_proto_msgTypes,
	}.Build()
	File_gateway_control_v1_wasm_proto = out.File
	file_gateway_control_v1_wasm_proto_goTypes = nil
	file_gateway_control_v1_wasm_proto_depIdxs = nil
}
